/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package es.altia.chd.form.ticket.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ticket service. Represents a row in the &quot;CHDTICKET_Ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>es.altia.chd.form.ticket.sb.model.impl.TicketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>es.altia.chd.form.ticket.sb.model.impl.TicketImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ticket
 * @generated
 */
@ProviderType
public interface TicketModel extends BaseModel<Ticket> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket model instance should use the {@link Ticket} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket.
	 *
	 * @return the primary key of this ticket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket.
	 *
	 * @param primaryKey the primary key of this ticket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ticket.
	 *
	 * @return the ID of this ticket
	 */
	public long getId();

	/**
	 * Sets the ID of this ticket.
	 *
	 * @param id the ID of this ticket
	 */
	public void setId(long id);

	/**
	 * Returns the form instance record ID of this ticket.
	 *
	 * @return the form instance record ID of this ticket
	 */
	public long getFormInstanceRecordId();

	/**
	 * Sets the form instance record ID of this ticket.
	 *
	 * @param formInstanceRecordId the form instance record ID of this ticket
	 */
	public void setFormInstanceRecordId(long formInstanceRecordId);

	/**
	 * Returns the form instance ID of this ticket.
	 *
	 * @return the form instance ID of this ticket
	 */
	public long getFormInstanceId();

	/**
	 * Sets the form instance ID of this ticket.
	 *
	 * @param formInstanceId the form instance ID of this ticket
	 */
	public void setFormInstanceId(long formInstanceId);

	/**
	 * Returns the group ID of this ticket.
	 *
	 * @return the group ID of this ticket
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ticket.
	 *
	 * @param groupId the group ID of this ticket
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this ticket.
	 *
	 * @return the create date of this ticket
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket.
	 *
	 * @param createDate the create date of this ticket
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the ticket ID of this ticket.
	 *
	 * @return the ticket ID of this ticket
	 */
	@AutoEscape
	public String getTicketId();

	/**
	 * Sets the ticket ID of this ticket.
	 *
	 * @param ticketId the ticket ID of this ticket
	 */
	public void setTicketId(String ticketId);

	/**
	 * Returns the token of this ticket.
	 *
	 * @return the token of this ticket
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this ticket.
	 *
	 * @param token the token of this ticket
	 */
	public void setToken(String token);

	/**
	 * Returns the email of this ticket.
	 *
	 * @return the email of this ticket
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this ticket.
	 *
	 * @param email the email of this ticket
	 */
	public void setEmail(String email);

	@Override
	public Ticket cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}